---
- include_vars: ../vault/credentials.yml
  when: mysql_root_password is undefined

- name: "Install MySQL database packages"
  become: true
  apt:
    name: "{{ item }}"
    cache_valid_time: "{{ apt_cache_timeout }}"
    state: present
  with_items:
    - "{{ mysql_packages }}"

- name: Start the MySQL service
  become: true
  service:
    name: mysql
    state: started
    enabled: true

- name: Secure MySQL installation
  become: true
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Deletes anonymous MySQL server user
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items:
      - 127.0.0.1
      - ::1
      - localhost
      - "*"
      - "{{ hostname }}"

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
