---
- name: Check if ultimate vim repository exists
  become: true
  stat:
    path: /root/.vim_runtime
  register: ultimate_vim_stat_result

- name: Clone ultimate vim repository
  become: true
  git:
    repo: git://github.com/amix/vimrc
    dest: /root/.vim_runtime/
    version: master
  when: ultimate_vim_stat_result.stat.exists == False

- name: Makeing Ultimate vim installer executable
  become: true
  file: dest=/root/.vim_runtime/install_awesome_vimrc.sh mode=a+x
  when: ultimate_vim_stat_result.stat.exists == False

- name: Check if custom vim config file is created
  become: true
  stat:
    path: /root/.vim_runtime/my_configs.vim
  register: custom_vim_config_stat_result

- name: Install ultimate vim
  become: true
  shell: /root/.vim_runtime/install_awesome_vimrc.sh
  when: custom_vim_config_stat_result.stat.exists == False

- name: Show line nubmers in vim
  become: true
  template:
    src: ../files/vim/my_configs.vim.j2
    dest: /root/.vim_runtime/my_configs.vim
  when: custom_vim_config_stat_result.stat.exists == False
