---
- name: Add ondrej ppa for php
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP packages
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_timeout }}"
    state: present
  with_items:
    - "{{ php_packages }}"

- name: Check if php.ini file exists
  become: true
  stat:
    path: /etc/php/7.2/fpm/php.ini
  register: php_ini_stat_result

- name: Copy php.ini file
  become: True
  template:
    src: ../templates/php/php.ini
    dest: /etc/php/7.2/fpm/php.ini
  when: php_ini_stat_result.stat.exists == False
  notify: restart php7.2-fpm
