---
php_packages:
  - php7.2
  - php7.2-fpm
  - php7.2-cli
  - php7.2-mysql
  - php7.2-curl
  - php7.2-gd
  - php7.2-intl
  - php-memcached
  - php7.2-zip
  - php7.2-dom
  - php7.2-mbstring
  - php7.2-mysql
